add team page
baza-trainee/eng-for-uarmy pull request #32
Opened 2023-09-14 15:29 UTC by Antifishka

2023-09-14 16:56 UTC, tumanchyk requested changes

2023-09-14 16:56 UTC, tumanchyk commented on app/[locale]/components/Team/Members/Members.module.scss
> +    gap: 20px;
ми уникаєм виковистання gap, бо на сафарі не підтримує такої властивості

2023-09-14 16:56 UTC, tumanchyk commented on app/[locale]/components/Team/Members/Members.jsx
> +            <ul className={styles.members__list}>
дуже великий файл краще зробити json файл в якому масив обєктів з інформацією про учасників, і тоді  obj.map(), (зараз це не обов'язково)

2023-09-14 16:56 UTC, tumanchyk commented on app/[locale]/components/Team/Members/Members.jsx
> +                    <Image src="/team/member-03.jpg" alt="member 3" width={265} height={266} />
тут потрібно зробити клас який обрізатиме кутик, по прикладу кнопки що у нас є

2023-09-14 19:40 UTC, Antifishka commented on app/[locale]/components/Team/Members/Members.jsx
> +            <ul className={styles.members__list}>
на наступний пул зроблю

2023-09-14 19:41 UTC, Antifishka commented on app/[locale]/components/Team/Members/Members.jsx
> +                    <Image src="/team/member-03.jpg" alt="member 3" width={265} height={266} />
на наступний пул зроблю

2023-09-14 19:42 UTC, Antifishka commented on app/[locale]/components/Team/Members/Members.module.scss
> +    gap: 20px;
дивилась на can I use, що підтримується safari

2023-09-15 06:11 UTC, tumanchyk approved these changes

2023-09-15 06:11 UTC, merged